# Import required modules

In [1]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.filterwarnings('ignore')

import scanpy as sc
import anndata
import pandas as pd
import numpy as np

In [2]:
import session_info
session_info.show()

# Function

In [3]:
def clean_adata(adata,
                obs_keep=None,
                uns_keep=None,
                obsm_keep=None,
                obsp_keep=None):
    """
    Keep only specified keys in AnnData slots.

    Parameters
    ----------
    adata : AnnData
    obs_keep : list
        Columns in adata.obs to keep
    uns_keep : list
        Keys in adata.uns to keep
    obsm_keep : list
        Keys in adata.obsm to keep
    obsp_keep : list
        Keys in adata.obsp to keep
    """

    if obs_keep is not None:
        drop = [c for c in adata.obs.columns if c not in obs_keep]
        adata.obs.drop(columns=drop, inplace=True)

    if uns_keep is not None:
        drop = [k for k in list(adata.uns.keys()) if k not in uns_keep]
        for k in drop:
            del adata.uns[k]

    if obsm_keep is not None:
        drop = [k for k in list(adata.obsm.keys()) if k not in obsm_keep]
        for k in drop:
            del adata.obsm[k]

    if obsp_keep is not None:
        drop = [k for k in list(adata.obsp.keys()) if k not in obsp_keep]
        for k in drop:
            del adata.obsp[k]

    return adata

# Variables

In [4]:
adatasd_path = '/rfs/project/rfs-iCNyzSAaucw/kk837/data_objects/Foetal/Visium/visium_foetal_healthy-all_raw.h5ad'
adatahd_path = '/rfs/project/rfs-iCNyzSAaucw/kk837/data_objects/Foetal/VisiumHD/Revision_Oct2025/all_b2c_cells_filtered_niche-sel_raw.h5ad'

In [5]:
save_dir = '/rfs/project/rfs-iCNyzSAaucw/kk837/data_objects/Foetal/TissueTypist/adata_for_training'

# Read in adata

In [6]:
adata_sd = sc.read_h5ad(adatasd_path)
adata_sd

AnnData object with n_obs × n_vars = 39223 × 33562
    obs: 'array_row', 'array_col', 'sample', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'mt_frac', 'sangerID', 'Publication', 'combinedID', 'donor', 'donor_type', 'region', 'region_finest', 'age', 'gender', 'facility', 'cell_or_nuclei', 'modality', 'kit_10x', 'flushed', 'status', 'cell2loc-map_group', 'JC_edit', 'sample_for_cell2loc', 'week', 'leiden', 'region_cluster', 'AtrialCardiomyocytesLeft', 'AtrialCardiomyocytesRight', 'VentricularCardiomyocytesLeftCompact', 'VentricularCardiomyocytesRightCompact', 'VentricularCardiomyocytesLeftTrabeculated', 'VentricularCardiomyocytesRightTrabeculated', 'SinoatrialNodeCardiomyocytes', 'AtrioventricularNodeCardiomyocytes', 'VentricularConductionSystemProximal', 'VentricularConductionSystemDistal', 'GreatVesselAdventitialFibroblasts'

In [7]:
adata_hd = sc.read_h5ad(adatahd_path)
adata_hd

AnnData object with n_obs × n_vars = 215913 × 18085
    obs: 'object_id', 'bin_count', 'array_row', 'array_col', 'labels_joint_source', 'in_tissue_manual', 'library', 'donor_section_ID', 'per-frame_donorIDs', 'donor', 'CS', 'est_CS', 'GA', 'PCW', 'section_ID', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'library_donor', 'n_genes', 'scVI_latent_n-layers-3_leiden_0.2', 'scVI_latent_n-layers-3_leiden_0.3', 'scVI_latent_n-layers-3_leiden_0.4', 'scVI_latent_n-layers-3_leiden_0.5', 'scVI_latent_n-layers-3_leiden_0.8', 'scVI_latent_n-layers-3_leiden_1.0', 'scVI_latent_n-layers-3_leiden_1.5', 'scVI_latent_n-layers-3_leiden_2.0', 'scVI_latent_n-layers-3_leiden_3.0', 'scVI_latent_n-layers-3_leiden_4.0', 'coarse_grain_pre', 'coarse_grain_pre_2', 'coarse_grain_tacco_ref-hd-sc

In [8]:
adata_hd.uns['spatial']['HEA_FOET14880396']['scalefactors']

{'bin_size_um': np.float64(2.0),
 'fiducial_diameter_fullres': np.float64(1491.317042123877),
 'microns_per_pixel': np.float64(0.22128091524390184),
 'regist_target_img_scalef': np.float64(0.15219156),
 'spot_diameter_fullres': np.float64(39.81352905874629),
 'tissue_0.3_mpp_150_buffer_scalef': np.float64(0.7376030508130061),
 'tissue_hires_scalef': np.float64(0.15219156),
 'tissue_lowres_scalef': np.float64(0.015219156)}

In [9]:
adata_hd.uns['spatial']['CellTalkHHD_Human_13_BRC2757-2758-7']['scalefactors']

{'bin_size_um': np.float64(2.0),
 'fiducial_diameter_fullres': np.float64(2412.0855756838937),
 'microns_per_pixel': np.float64(0.13681106645913083),
 'regist_target_img_scalef': np.float64(0.12597896),
 'spot_diameter_fullres': np.float64(58.03836118313326),
 'tissue_0.3_mpp_150_buffer_scalef': np.float64(0.45603688819710275),
 'tissue_hires_scalef': np.float64(0.12597896),
 'tissue_lowres_scalef': np.float64(0.012597896)}

In [10]:
adata_hd.uns['spatial'].keys()

dict_keys(['CellTalkHHD_Human_13_BRC2757-2758-7', 'HEA_FOET14880396'])

In [11]:
adata_hd.obs[["donor", "section_ID","library"]].drop_duplicates()

,donor,section_ID,library
HEA_FOET14880396___1,C194,HEA_FOET14880396__C194__1,HEA_FOET14880396
CellTalkHHD_Human_13_BRC2757-2758-7___2,BRC2758,CellTalkHHD_Human_13_BRC2757-2758-7__BRC2758__1,CellTalkHHD_Human_13_BRC2757-2758-7
CellTalkHHD_Human_13_BRC2757-2758-7___15769,BRC2757,CellTalkHHD_Human_13_BRC2757-2758-7__BRC2757__2,CellTalkHHD_Human_13_BRC2757-2758-7
CellTalkHHD_Human_13_BRC2757-2758-7___21057,BRC2757,CellTalkHHD_Human_13_BRC2757-2758-7__BRC2757__1,CellTalkHHD_Human_13_BRC2757-2758-7
CellTalkHHD_Human_13_BRC2757-2758-7___52250,BRC2758,CellTalkHHD_Human_13_BRC2757-2758-7__BRC2758__2,CellTalkHHD_Human_13_BRC2757-2758-7


# Remove "Adventitia - Coronary" spots

- We have observed that including ‘Adventitia - Coronary’ spots in the training dataset disrupts prediction accuracy.
- Therefore, we will remove the corresponding spots (1810 spots) form the SD data. HD data doesn't have this annotation.

In [12]:
adata_sd = adata_sd[adata_sd.obs['annotation_final_mod']!='Adventitia - Coronary'].copy()
pd.crosstab(adata_sd.obs['niche_fine_Mar2026'],
            adata_sd.obs['modality'],
           )

modality,Visium,Visium-FFPE
niche_fine_Mar2026,,
AV node,58,45
AV ring,196,154
Atrial myocardium - non-terminal category,1869,1619
Connective tissue,879,241
Coronary vessel,51,88
Ductus arteriosus,71,0
Endocardial cushion - Valve,301,771
Endocardium - Atrial,318,137
Endocardium - Ventricular,1800,6


# Clean up the obs columns, etc

In [13]:
obs_keep = ['array_row', 'array_col', 'sample', 'sample_for_cell2loc',
            'sangerID', 'Publication', 'combinedID', 
            'donor', 'donor_type', 'region', 'region_finest', 
            'age', 'gender', 'facility', 'modality', 'kit_10x',
             'week','niche_fine_Apr2026', 'niche_coarse_Apr2026']
uns_keep = []
obsm_keep = ['spatial']
obsp_keep = []

adata_sd = clean_adata(adata_sd,
                        obs_keep=obs_keep,uns_keep=uns_keep,
                        obsm_keep=obsm_keep,obsp_keep=obsp_keep)
adata_sd

AnnData object with n_obs × n_vars = 37413 × 33562
    obs: 'array_row', 'array_col', 'sample', 'sangerID', 'Publication', 'combinedID', 'donor', 'donor_type', 'region', 'region_finest', 'age', 'gender', 'facility', 'modality', 'kit_10x', 'sample_for_cell2loc', 'week', 'niche_fine_Apr2026', 'niche_coarse_Apr2026'
    var: 'gene_ids'
    obsm: 'spatial'

In [14]:
obs_keep = ['section_ID','object_id', 'bin_count', 'array_row', 'array_col', 
            'labels_joint_source', 'library', 
            'donor_section_ID', 'per-frame_donorIDs', 'donor', 'CS', 'est_CS', 'GA', 'PCW',  'coarse_grain_tacco_ref-hd-scn','fine_grain_2Feb2026_mod', 
            'niche_fine_Apr2026', 'niche_coarse_Apr2026']
uns_keep = [] # remove "spatial" from here to reduce the file size.
obsm_keep = ['spatial']
obsp_keep = []

adata_hd = clean_adata(adata_hd,
                        obs_keep=obs_keep,uns_keep=uns_keep,
                        obsm_keep=obsm_keep,obsp_keep=obsp_keep)
adata_hd

AnnData object with n_obs × n_vars = 215913 × 18085
    obs: 'object_id', 'bin_count', 'array_row', 'array_col', 'labels_joint_source', 'library', 'donor_section_ID', 'per-frame_donorIDs', 'donor', 'CS', 'est_CS', 'GA', 'PCW', 'section_ID', 'coarse_grain_tacco_ref-hd-scn', 'fine_grain_2Feb2026_mod', 'niche_fine_Apr2026', 'niche_coarse_Apr2026'
    var: 'gene_ids', 'feature_types', 'genome', 'mt', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts'
    obsm: 'spatial'

# Align some .obs.columns

In [15]:
adata_sd.obs.rename(columns={'sample':'section_ID',
                             'sangerID':'library',
                             'week':'PCW',
                            },
                    inplace=True)
adata_sd

AnnData object with n_obs × n_vars = 37413 × 33562
    obs: 'array_row', 'array_col', 'section_ID', 'library', 'Publication', 'combinedID', 'donor', 'donor_type', 'region', 'region_finest', 'age', 'gender', 'facility', 'modality', 'kit_10x', 'sample_for_cell2loc', 'PCW', 'niche_fine_Apr2026', 'niche_coarse_Apr2026'
    var: 'gene_ids'
    obsm: 'spatial'

In [16]:
# modality
adata_sd.obs.replace({'modality':{
    'Visium-FFPE':'VisiumSD-FFPE',
    'Visium':'VisiumSD-3prime'
}},inplace=True)
adata_hd.obs['modality'] = 'VisiumHD-FFPE'

print(adata_sd.obs['modality'].value_counts())
print(adata_hd.obs['modality'].value_counts())

modality
VisiumSD-3prime    19179
VisiumSD-FFPE      18234
Name: count, dtype: int64
modality
VisiumHD-FFPE    215913
Name: count, dtype: int64


# Save 

In [17]:
# split SD data into 3p and FFPE
adata_sd_3p = adata_sd[adata_sd.obs['modality']=='VisiumSD-3prime'].copy()
print(adata_sd_3p.shape)
adata_sd_ffpe = adata_sd[adata_sd.obs['modality']=='VisiumSD-FFPE'].copy()
print(adata_sd_ffpe.shape)

(19179, 33562)
(18234, 33562)


In [18]:
# save
adata_sd_3p.write(f'{save_dir}/adata_sd_3p_raw.h5ad')
adata_sd_ffpe.write(f'{save_dir}/adata_sd_ffpe_raw.h5ad')
adata_hd.write(f'{save_dir}/adata_hd_raw.h5ad')

# confirming these are raw counts
print(adata_sd_3p.X.data[:10])
print(adata_sd_ffpe.X.data[:10])
print(adata_hd.X.data[:10])

[  1.  42.   1. 127.  35. 138.  51.   1. 118. 174.]
[308.  36.  58. 486. 168. 138. 497. 542. 247.   6.]
[1. 1. 1. 1. 1. 1. 1. 2. 1. 1.]


In [19]:
save_dir

'/rfs/project/rfs-iCNyzSAaucw/kk837/data_objects/Foetal/TissueTypist/adata_for_training'

In [20]:
!ls -lh {save_dir}

total 2.0G
-rwxrwx---+ 1 kk837 kk837 1.8G Apr 22 16:31 adata_hd_raw.h5ad
-rwxrwx---+ 1 kk837 kk837 575M Apr 22 16:30 adata_sd_3p_raw.h5ad
-rwxrwx---+ 1 kk837 kk837 956M Apr 22 16:30 adata_sd_ffpe_raw.h5ad
drwxrwx---+ 2 kk837 kk837  113 Apr 22 16:25 archived_22Apr2026


In [21]:
adata_hd.obs

,object_id,bin_count,array_row,array_col,labels_joint_source,library,donor_section_ID,per-frame_donorIDs,donor,CS,est_CS,GA,PCW,section_ID,coarse_grain_tacco_ref-hd-scn,fine_grain_2Feb2026_mod,niche_fine_Apr2026,niche_coarse_Apr2026,modality
HEA_FOET14880396___1,1,31,2932.612903,334.000000,primary,HEA_FOET14880396,NaN,C194,C194,NaN,NaN,11w0d,9w0d,HEA_FOET14880396__C194__1,LymphoidCells,unclassified,Coronary vessel,Vasculature,VisiumHD-FFPE
HEA_FOET14880396___2,2,26,2959.346154,336.923077,primary,HEA_FOET14880396,NaN,C194,C194,NaN,NaN,11w0d,9w0d,HEA_FOET14880396__C194__1,LymphoidCells,InnateLymphoidCells,Coronary vessel,Vasculature,VisiumHD-FFPE
HEA_FOET14880396___3,3,32,2882.562500,334.187500,primary,HEA_FOET14880396,NaN,C194,C194,NaN,NaN,11w0d,9w0d,HEA_FOET14880396__C194__1,MyeloidCells,MacrophagesLYVE1pos,Coronary vessel,Vasculature,VisiumHD-FFPE
HEA_FOET14880396___5,5,35,2870.714286,305.171429,primary,HEA_FOET14880396,NaN,C194,C194,NaN,NaN,11w0d,9w0d,HEA_FOET14880396__C194__1,MesenchymalCells,Fibroblasts,Epicardial region,Epicardial region,VisiumHD-FFPE
HEA_FOET14880396___6,6,31,2877.612903,308.000000,primary,HEA_FOET14880396,NaN,C194,C194,NaN,NaN,11w0d,9w0d,HEA_FOET14880396__C194__1,MesenchymalCells,Fibroblasts,Coronary vessel,Vasculature,VisiumHD-FFPE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CellTalkHHD_Human_13_BRC2757-2758-7___289086,289086,5,1019.200000,2912.600000,secondary,CellTalkHHD_Human_13_BRC2757-2758-7,BRC2758__2,"BRC2757,BRC2758",BRC2758,15,16,7w1d,5w1d,CellTalkHHD_Human_13_BRC2757-2758-7__BRC2758__2,AtrialCardiomyocytes,AtrialCardiomyocytesRight,Atrium - Right,Atrium,VisiumHD-FFPE
CellTalkHHD_Human_13_BRC2757-2758-7___289093,289093,7,1087.285714,2794.428571,secondary,CellTalkHHD_Human_13_BRC2757-2758-7,BRC2758__2,"BRC2757,BRC2758",BRC2758,15,16,7w1d,5w1d,CellTalkHHD_Human_13_BRC2757-2758-7__BRC2758__2,MesenchymalCells,Fibroblasts,Epicardial region,Epicardial region,VisiumHD-FFPE
CellTalkHHD_Human_13_BRC2757-2758-7___289189,289189,5,1076.800000,2851.000000,secondary,CellTalkHHD_Human_13_BRC2757-2758-7,BRC2758__2,"BRC2757,BRC2758",BRC2758,15,16,7w1d,5w1d,CellTalkHHD_Human_13_BRC2757-2758-7__BRC2758__2,AtrialCardiomyocytes,AtrialCardiomyocytesRight,Atrium - Right,Atrium,VisiumHD-FFPE
CellTalkHHD_Human_13_BRC2757-2758-7___289214,289214,6,1093.000000,3095.833333,secondary,CellTalkHHD_Human_13_BRC2757-2758-7,BRC2758__2,"BRC2757,BRC2758",BRC2758,15,16,7w1d,5w1d,CellTalkHHD_Human_13_BRC2757-2758-7__BRC2758__2,AtrialCardiomyocytes,Erythrocytes,Atrium - Right,Atrium,VisiumHD-FFPE


In [22]:
# Run on each h5ad to audit column names and unique values
for ad, name in [
    (adata_sd_3p,   "SD_3prime"),
    (adata_sd_ffpe, "SD_FFPE"),
    (adata_hd,      "HD_raw"),
]:
    print(f"\n=== {name} ===")
    print(f"obs columns: {list(ad.obs.columns)}")
    print(f"section col values: {ad.obs.get('sample', ad.obs.get('section_ID', 'NOT FOUND')).unique()[:5].tolist()}")
    for col in ["niche_coarse_Mar2026", "niche_fine_Mar2026"]:
        if col in ad.obs.columns:
            print(f"{col}: {sorted(ad.obs[col].dropna().unique().tolist())}")


=== SD_3prime ===
obs columns: ['array_row', 'array_col', 'section_ID', 'library', 'Publication', 'combinedID', 'donor', 'donor_type', 'region', 'region_finest', 'age', 'gender', 'facility', 'modality', 'kit_10x', 'sample_for_cell2loc', 'PCW', 'niche_fine_Apr2026', 'niche_coarse_Apr2026']
section col values: ['HCAHeartST10298114', 'HCAHeartST10298115', 'HCAHeartST10298116', 'HCAHeartST10298117', 'HCAHeartST10298120']

=== SD_FFPE ===
obs columns: ['array_row', 'array_col', 'section_ID', 'library', 'Publication', 'combinedID', 'donor', 'donor_type', 'region', 'region_finest', 'age', 'gender', 'facility', 'modality', 'kit_10x', 'sample_for_cell2loc', 'PCW', 'niche_fine_Apr2026', 'niche_coarse_Apr2026']
section col values: ['BHF_F_Hea13295830', 'BHF_F_Hea13295831']

=== HD_raw ===
obs columns: ['object_id', 'bin_count', 'array_row', 'array_col', 'labels_joint_source', 'library', 'donor_section_ID', 'per-frame_donorIDs', 'donor', 'CS', 'est_CS', 'GA', 'PCW', 'section_ID', 'coarse_grain_ta